import enum

class EventType(enum.Enum):
    FACIAL_MATCH_SUCCESS = "FACIAL_MATCH_SUCCESS"
    FACIAL_MATCH_FAILED = "FACIAL_MATCH_FAILED"
    FACIAL_MATCH_ERROR = "FACIAL_MATCH_ERROR"
    FAULT_DETECT_SUCCESS = "FAULT_DETECT_SUCCESS"
    NO_FAULT_DETECTED = "NO_FAULT_DETECTED"
    IMAGE_CAPTURE_SUCCESS = "IMAGE_CAPTURE_SUCCESS"
    IMAGE_CAPTURE_FAILED = "IMAGE_CAPTURE_FAILED"
