"""empty message

Revision ID: 32abd70fa9ce
Revises: f03f3d419bca
Create Date: 2022-03-24 16:53:20.924881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32abd70fa9ce'
down_revision = 'f03f3d419bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('event', sa.Column('image_link', sa.String(length=200), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('event', 'image_link')
    op.drop_column('event', 'name')
    # ### end Alembic commands ###
