"""Added heartbeat and primary_camera

Revision ID: 481087a30454
Revises: 32abd70fa9ce
Create Date: 2022-03-29 11:34:41.098763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481087a30454'
down_revision = '32abd70fa9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('last_heartbeat', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('primary_camera', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'camera', ['primary_camera'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'primary_camera')
    op.drop_column('camera', 'last_heartbeat')
    # ### end Alembic commands ###
