"""empty message

Revision ID: e01517460d51
Revises: 481087a30454
Create Date: 2022-03-31 16:31:45.539570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01517460d51'
down_revision = '481087a30454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_primary_camera_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_primary_camera_fkey', 'users', 'camera', ['primary_camera'], ['id'])
    # ### end Alembic commands ###
